### ISSUE TITLE
processing of -javaagent failed, processJavaStart failed

### ISSUE THREAD

**Issue by seckinu** [dogboy21/serializationisbad#29]
```java
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
        at io.dogboy.serializationisbad.core.SerializationIsBad.<clinit>(SerializationIsBad.java:14)
        at io.dogboy.serializationisbad.agent.SerializationIsBadAgent.premain(SerializationIsBadAgent.java:11)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 8 more
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message Outstanding error when calling method in invokeJavaAgentMainMethod at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 619
*** java.lang.instrument ASSERTION FAILED ***: "success" with message invokeJavaAgentMainMethod failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 459
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
```

when I add the mod to the jvm arguments in my server I get this crash above, my server is as follows:
-1.18.2
-forge 40.2.9

**Comment by Exaxxion** [comment]
When you are using Forge mod loader on Minecraft 1.7 or newer, as the README states, you simply drop it in the mods folder.

The launch arguments to use it as a Java Agent are in the event that you are running on a version prior to MC 1.7 or you are not using Forge as your mod loader.

**Comment by seckinu** [comment]
Ah I misread, apologies.
