### ISSUE TITLE
processJavaStart failed when using javaagent

### ISSUE THREAD

**Issue by Jan-DT** [dogboy21/serializationisbad#3]
Whenever I try to start my Fabric 1.20.1 server (latest build, installed yesterday) using this as javaagent, I am getting the following error:
```
WARNING: Using incubator modules: jdk.incubator.vector
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
        at io.dogboy.serializationisbad.core.SerializationIsBad.<clinit>(SerializationIsBad.java:14)
        at io.dogboy.serializationisbad.agent.SerializationIsBadAgent.premain(SerializationIsBadAgent.java:11)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 8 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at t:\workspace\open\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
```

I am using the following startup parameters:
`java -javaagent:serializationisbad-1.3.jar -Xms5120M -Xmx5120M --add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -jar fabric.jar --nogui`

Is there something I am doing wrong here, or is this an issue with serializationisbad?

**Comment by AstraKurai** [comment]
but 1.20.1 isnt affected..

**Comment by Jan-DT** [comment]
Really? I wasn't aware. I thought versions outside of 1.7.* / 1.12.* still had a chance to be affected. Anyways, thanks for the quick response.

**Comment by dogboy21** [comment]
It looks like thats some sort of incompatibility with Fabric. Thank you, I will take a look at it!

> Really? I wasn't aware. I thought versions outside of 1.7.* / 1.12.* still had a chance to be affected. Anyways, thanks for the quick response.

While we currently don't know of any cases in 1.20, there's always a little chance that there are affected mods.

**Comment by Jan-DT** [comment]
Seems to be working now! Thanks :)
