### ISSUE TITLE
`NullPointerException` on Minecraft 1.6.4 with Cauldron

### ISSUE THREAD

**Issue by tomodachi94** [dogboy21/serializationisbad#34]
Log:
<details><summary>Log</summary>
<p>

```log
[30.07 09:34:36] [Server] java.lang.NoClassDefFoundErrororg/apache/logging/log4j/LogManager
[30.07 09:34:36] [Server] 	at io.dogboy.serializationisbad.core.SerializationIsBad.<clinit>(SerializationIsBad.java:14)
[30.07 09:34:36] [Server] 	at io.dogboy.serializationisbad.legacyforge.SerializationIsBadCoreMod.<init>(SerializationIsBadCoreMod.java:16)
[30.07 09:34:36] [Server] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[30.07 09:34:36] [Server] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[30.07 09:34:36] [Server] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[30.07 09:34:36] [Server] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[30.07 09:34:36] [Server] 	at java.lang.Class.newInstance(Unknown Source)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:427)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:310)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:212)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:74)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:20)
[30.07 09:34:36] [Server] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:111)
[30.07 09:34:36] [Server] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
[30.07 09:34:36] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[30.07 09:34:36] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[30.07 09:34:36] [Server] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[30.07 09:34:36] [Server] 	at java.lang.reflect.Method.invoke(Unknown Source)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[30.07 09:34:36] [Server] Caused byjava.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
[30.07 09:34:36] [Server] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
[30.07 09:34:36] [Server] 	at java.lang.ClassLoader.loadClass(Unknown Source)
[30.07 09:34:36] [Server] 	at java.lang.ClassLoader.loadClass(Unknown Source)
[30.07 09:34:36] [Server] 	... more
[30.07 09:34:36] [Server] Caused byjava.lang.NullPointerException
[30.07 09:34:36] [Server] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
[30.07 09:34:36] [Server] 	... more
[30.07 09:34:36] [Server] [SEVERE] [ForgeModLoader] An error occurred trying to configure the minecraft home at /. for Forge Mod Loader
[30.07 09:34:36] [Server] java.lang.NoClassDefFoundErrororg/apache/logging/log4j/LogManager
[30.07 09:34:36] [Server] 	at io.dogboy.serializationisbad.core.SerializationIsBad.<clinit>(SerializationIsBad.java:14)
[30.07 09:34:36] [Server] 	at io.dogboy.serializationisbad.legacyforge.SerializationIsBadCoreMod.<init>(SerializationIsBadCoreMod.java:16)
[30.07 09:34:36] [Server] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[30.07 09:34:36] [Server] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[30.07 09:34:36] [Server] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[30.07 09:34:36] [Server] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[30.07 09:34:36] [Server] 	at java.lang.Class.newInstance(Unknown Source)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:427)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:310)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:212)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:74)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:20)
[30.07 09:34:36] [Server] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:111)
[30.07 09:34:36] [Server] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
[30.07 09:34:36] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[30.07 09:34:36] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[30.07 09:34:36] [Server] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[30.07 09:34:36] [Server] 	at java.lang.reflect.Method.invoke(Unknown Source)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[30.07 09:34:36] [Server] Caused byjava.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
[30.07 09:34:36] [Server] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
[30.07 09:34:36] [Server] 	at java.lang.ClassLoader.loadClass(Unknown Source)
[30.07 09:34:36] [Server] 	at java.lang.ClassLoader.loadClass(Unknown Source)
[30.07 09:34:36] [Server] 	... more
[30.07 09:34:36] [Server] Caused byjava.lang.NullPointerException
[30.07 09:34:36] [Server] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
[30.07 09:34:36] [Server] 	... more
[30.07 09:34:36] [Server] A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
[30.07 09:34:36] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[30.07 09:34:36] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[30.07 09:34:36] [Server] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[30.07 09:34:36] [Server] 	at java.lang.reflect.Method.invoke(Unknown Source)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[30.07 09:34:36] [Server] 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[30.07 09:34:36] [Server] Caused byjava.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
[30.07 09:34:36] [Server] 	at io.dogboy.serializationisbad.core.SerializationIsBad.<clinit>(SerializationIsBad.java:14)
[30.07 09:34:36] [Server] 	at io.dogboy.serializationisbad.legacyforge.SerializationIsBadCoreMod.<init>(SerializationIsBadCoreMod.java:16)
```

</p>
</details>

**Comment by tomodachi94** [comment]
Looks like this *might* be fixed by 5e3315cbfcf839f5fa2c4f4f59e0f0e220b4fef3?

**Comment by dogboy21** [comment]
Yep! We're currently working on a fix for that specific problem, which also affects Fabric servers (#3)

**Comment by Aiidoneus** [comment]
Can you try the latest release version? https://github.com/dogboy21/serializationisbad/releases/tag/1.4 and tell us if the issue is still there?

**Comment by tomodachi94** [comment]
The server starts, awesome job! Thank you for fixing that so quickly.
