### ISSUE TITLE
Failed to launch on quilt server for 1.20.1

### ISSUE THREAD

**Issue by ryleu** [dogboy21/serializationisbad#44]
Here's my launch command:

```bash
#!/usr/bin/env bash
java -jar packwiz-installer-bootstrap.jar -g -s server http://ryleu.me/super-awesome-adventure-pack/main/pack.toml
java -Xmx4G -javaagent:serializationisbad-1.3.jar -jar quilt-server-launch.jar nogui
```

Here's the output:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at io.dogboy.serializationisbad.core.SerializationIsBad.<clinit>(SerializationIsBad.java:14)
	at io.dogboy.serializationisbad.agent.SerializationIsBadAgent.premain(SerializationIsBadAgent.java:11)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 8 more
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message Outstanding error when calling method in invokeJavaAgentMainMethod at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 619
*** java.lang.instrument ASSERTION FAILED ***: "success" with message invokeJavaAgentMainMethod failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 459
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
./start.sh: line 3: 1201702 Aborted                 (core dumped) java -Xmx4G -javaagent:serializationisbad-1.3.jar -jar quilt-server-launch.jar nogui
```

Here's a screenshot of my terminal:

![image](https://github.com/dogboy21/serializationisbad/assets/69326171/1bc25496-847a-410f-a864-1fa3de9f2b43)

Not sure what the fix is here. Am I simply using the launch command incorrectly?

**Comment by dogboy21** [comment]
If you want to test if that fixes your problem, you could test the jar file that's inside [this zip file](https://github.com/dogboy21/serializationisbad/suites/14703142845/artifacts/834852528)

**Comment by ryleu** [comment]
I'll give it a try after lunch, give me an hour or so.

**Comment by ryleu** [comment]
![image](https://github.com/dogboy21/serializationisbad/assets/69326171/7e3a2113-8007-4b82-a889-578f49c6cd62)
looks like it loaded and successfully redirected immersive paintings' serializer invocation

**Comment by Aiidoneus** [comment]
This is closed as of latest release 1.4
