### ISSUE TITLE
[1.19.2]  Crash on Load

### ISSUE THREAD

**Issue by Reshy** [dogboy21/serializationisbad#77]
[04Sep2023 21:20:53.410] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, ReshyShira, --version, forge-43.2.21, --gameDir, E:\Personal\Archive\Games\Twitch MC\Instances\1.19.2 DS, --assetsDir, E:\Personal\Archive\Games\Twitch MC\Install\assets, --assetIndex, 1.19, --uuid, f88d39c334994aa8bdb42ceaa95cee0e, --accessToken, ????????, --clientId, YjMwMGJiY2ItNzVlZi00MmY2LWJhMTgtOTA3NWRjZjUxMjg2, --xuid, 2535471593108702, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.21, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[04Sep2023 21:20:53.417] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[04Sep2023 21:20:56.450] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/E:/Personal/Archive/Games/Twitch%20MC/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2397!/ Service=ModLauncher Env=CLIENT
[04Sep2023 21:20:56.540] [main/INFO] [io.dogboy.serializationisbad.core.SerializationIsBad/]: Initializing SerializationIsBad, implementation type: modlauncher
[04Sep2023 21:21:40.815] [main/ERROR] [io.dogboy.serializationisbad.core.SerializationIsBad/]: Failed to load remote config file
java.io.IOException: Invalid response code: 503
	at io.dogboy.serializationisbad.core.SerializationIsBad.readRemoteConfig(SerializationIsBad.java:121) ~[?:?]
	at io.dogboy.serializationisbad.core.SerializationIsBad.readConfig(SerializationIsBad.java:101) ~[?:?]
	at io.dogboy.serializationisbad.core.SerializationIsBad.<init>(SerializationIsBad.java:61) ~[?:?]
	at io.dogboy.serializationisbad.core.SerializationIsBad.init(SerializationIsBad.java:43) ~[?:?]
	at io.dogboy.serializationisbad.modlauncher.SerializationIsBadTransformationService.initialize(SerializationIsBadTransformationService.java:36) ~[?:?]
	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68) ~[modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:92) ~[modlauncher-10.0.8.jar%2388!/:?]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) [?:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:92) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:51) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:87) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
[04Sep2023 21:21:40.821] [main/INFO] [io.dogboy.serializationisbad.core.SerializationIsBad/]: Using local config file as a fallback

**Comment by dogboy21** [comment]
`[04Sep2023 21:21:40.815] [main/ERROR] [io.dogboy.serializationisbad.core.SerializationIsBad/]: Failed to load remote config file
java.io.IOException: Invalid response code: 503`

It looks like SiB was unable to load the remote config file from Github during the game startup (probably because of temporary issues on Githubs side).  You could try again after a few minutes which should solve the issue.

In [version 1.5](https://github.com/dogboy21/serializationisbad/releases/tag/1.5) this issue should be resolved due to local caching of the remote config file in case of temporary failure to read it from Github.

**Comment by dogboy21** [comment]
Fixed in [version 1.5](https://github.com/dogboy21/serializationisbad/releases/tag/1.5)

**Comment by xJon** [comment]
@dogboy21 This is happening again (https://github.com/xJon/Hexxit-II/issues/230), would shipping a modpack with `serializationisbad-remotecache.json` prevent this issue for fresh installs?
